### ISSUE TITLE
mkdir missing operand in install.sh

### ISSUE THREAD

**Issue by ieguiguren** [003random/003Recon#2]
As install.sh begins with:
`home_dir=$(pwd)

    dependencies_dir="dependencies"  

    mkdir $output_dir;
    mkdir $dependencies_dir; 
`

$output_dir is used before assigning it. Also home_dir is assigned but not used, though this won't arrise any error.

I guess there was some confusion declaring them.

**Comment by 003random** [comment]
You are indeed right! 
Thanks for pointing this out to me. I will push a fix  later today.
Thanks!
