### ISSUE TITLE
CORS & CRLF functions [[ Wpscan-subdoamins.sh & nmap // permission denied

### ISSUE THREAD

**Issue by attacker420** [003random/003Recon#7]
Hi,

While other functions are perfectly working but these two are not working:

CORS misconfiguration
CRLF injection
Wpscan-subdoamins.sh
nmap

I am getting this result after running the tool.
![re](https://user-images.githubusercontent.com/10330087/34328057-6bdee408-e8f6-11e7-8628-11bddfed58f9.PNG)

**Comment by attacker420** [comment]
I have updated the script install.sh but still having issue of permission denied for two tools mentioned above..

**Comment by 003random** [comment]
Give the script execute permissions and you are good to go :)

**Comment by attacker420** [comment]
@003random can you please guide me how to give permissions to tools.. what i have understood is to go to the tools folder and chmod all the tools?? but it will only make them executable ?

**Comment by 003random** [comment]
you can do chmod 777 /tools/crlf.sh to give it all permissions. Do the same for the other bash scripts and it should work
