### ISSUE TITLE
dependencies_dir defined twice in install.sh

### ISSUE THREAD

**Issue by JeremyCBrooks** [003random/003Recon#9]
First two lines of install.sh:
    dependencies_dir="dependencies"  
    dependencies_dir="output"  

It causes the install to fail unless it is changed to:
    dependencies_dir="dependencies"  
    output_dir="output"

**Comment by attacker420** [comment]
Dear ,

I am getting this error..
After I have updated the Install.sh file.

![screen shot 2018-01-19 at 4 38 30 pm](https://user-images.githubusercontent.com/10330087/35149277-486cab86-fd37-11e7-9862-c8ac831a0093.png)

**Comment by 003random** [comment]
Should be fixed now. thanks for the heads up :)
Appreciate it!
